Repository tuqulore/vue-3-practices, pull requests merged in 2024-12, with the labels that each got.

#645 スコープ付きスロットのリンクとサンプル
  docs/slides.md
Labels: documentation

#643 コンポーネントの説明をステップバイステップにおこなう
  docs/public/chat-component-example-1.png
  docs/public/chat-component-example-2.png
  docs/public/chat-component-example-3.png
  docs/public/whats_component.png
  docs/slides.md
Labels: documentation

#649 Nuxt のスライドの推敲 & useState() のハンズオン
  docs/slides.md
Labels: documentation

#658 リアクティビティの演習スライドを追加
  docs/slides.md
Labels: documentation

#665 HTML の記述に関する警告がスライドのビルド時表示される
  docs/slides.md
Labels: bug

#666 ツールガイド
  docs/slides.md
Labels: documentation

#659 教材の目標
  docs/slides.md
Labels: documentation

#660 Vue.js とは？の注釈をもう少し易しくする
  docs/slides.md
Labels: documentation

#661 Options API と Composition API の違いを明文化する
  docs/public/apis.png
  docs/slides.md
Labels: documentation

#663 スライドの最初の段落が薄い文字色になっているのをやめる
  docs/slides.md
  docs/style.css
Labels: enhancement

#662 リアクティブに関する推敲
  docs/slides.md
Labels: documentation

#667 最初のサンプルで SFC の説明をする
  docs/components/FirstSample.vue
  docs/slides.md
Labels: documentation

#669 ハンズオン環境の文書の更新
  docs/public/grid-component-example.png
  docs/public/stackblitz-example.png
  docs/public/vscode-example.png
  docs/public/vue-sfc-playground-example.png
  docs/slides.md
Labels: documentation

#664 テンプレート構文とコンポーネントの演習
  docs/slides.md
Labels: documentation

#674 書いて試せるようPlaygroundのリンクをつける & 公式 Doc リンクは興味がある人向けにする
  docs/slides.md
Labels: documentation

#675 動作しないサンプルコードの修正
  docs/slides.md
Labels: documentation

#672 算出関数 → 算出プロパティ
  docs/slides.md
Labels: documentation

#678 グリッドコンポーネントのリファクタリング
  docs/slides.md
Labels: documentation

#681 fix typo (補足→捕捉)
  docs/slides.md
Labels: documentation

#682 *-fetch-router-* にいくつかコメントを追加する
  handson-fetch-router-finish/src/components/PostDetail.vue
  handson-fetch-router-finish/src/main.js
  handson-fetch-router-nuxt-finish/pages/posts/[id].vue
  handson-fetch-router/src/components/PostDetail.vue
Labels: documentation

#680 Vue コンポーネントはファイルとしては .vue ファイルで構成される
  docs/slides.md
Labels: documentation

#687 パスワードチェッカーの更新
  docs/public/debounce.png
  docs/public/throttle.png
  docs/slides.md
Labels: documentation

#690 Nuxt ESLint Module のセットアップ
  .github/workflows/lint.yaml
  .vscode/settings.json
  handson-fetch-router-nuxt-finish/eslint.config.mjs
  handson-fetch-router-nuxt-finish/nuxt.config.js
  handson-fetch-router-nuxt-finish/package.json
  handson-nuxt-playground/eslint.config.mjs
  handson-nuxt-playground/nuxt.config.js
  handson-nuxt-playground/package.json
  handson-nuxt/eslint.config.mjs
  handson-nuxt/nuxt.config.js
  handson-nuxt/package.json
  handson-sticky/eslint.config.mjs
  handson-sticky/nuxt.config.js
  handson-sticky/package.json
  package.json
  practice-slot-answer/src/App.vue
  yarn.lock
Labels: enhancement

#691 type module 指定して CommonJS を使わないことにする
  docs/package.json
  handson-fetch-router-finish/package.json
  handson-fetch-router-nuxt-finish/package.json
  handson-fetch-router/package.json
  handson-gallery-shoes-cart-finish/package.json
  handson-gallery-shoes-finish/package.json
  handson-gallery-shoes/package.json
  handson-grid-component-finish/package.json
  handson-grid-component/package.json
  handson-nuxt-playground/package.json
  handson-nuxt/package.json
  handson-password-checker-finish/package.json
  handson-password-checker/package.json
  handson-sticky/package.json
  handson-vue-playground/package.json
  handson-vue/package.json
  package.json
  practice-computed-answer/package.json
  practice-computed/package.json
  practice-debounce-answer/package.json
  practice-debounce/package.json
  practice-emit-event-handling-answer/package.json
  practice-emit-event-handling/package.json
  practice-fetch-answer/package.json
  practice-fetch/package.json
  practice-mounted-answer/package.json
  practice-mounted/package.json
  practice-mustache-setup-answer/package.json
  practice-mustache-setup/package.json
  practice-reactive-class-binding-event-handling-answer/package.json
  practice-reactive-class-binding-event-handling/package.json
  practice-reactive-props-component-v-model-answer-1/package.json
  practice-reactive-props-component-v-model-answer-2/package.json
  practice-reactive-props-component-v-model-answer-3/package.json
  practice-reactive-props-component-v-model/package.json
  practice-scoped-css-component-answer/package.json
  practice-scoped-css-component/package.json
  practice-slot-answer/package.json
  practice-slot/package.json
  practice-style-answer/package.json
  practice-style/package.json
  practice-v-for-answer/package.json
  practice-v-for/package.json
  practice-v-if-answer/package.json
  practice-v-if/package.json
  practice-v-model-answer/package.json
  practice-v-model/package.json
  practice-vue-router-answer-1/package.json
  practice-vue-router-answer-2/package.json
  practice-vue-router/package.json
Labels: enhancement

#692 ダークモードでのコントラストが悪いところを調整する
  docs/components/ReactiveSample.vue
  docs/slides.md
Labels: bug

#697 yarn-deduplicate によるパッケージ依存関係の整理
  package.json
  yarn.lock
Labels: dependencies

#693 推敲
  README.md
  docs/package.json
  docs/slides.md
  handson-fetch-router-nuxt-finish/README.md
  handson-nuxt-playground/README.md
  handson-sticky/README.md
  package.json
Labels: documentation
